<a href="https://colab.research.google.com/github/hmmnyamminji/python/blob/main/%EC%84%9C%EC%9A%B8%EC%8B%9C%EC%A7%80%ED%95%98%EC%B2%A0%EA%B5%90%ED%86%B5%EB%9F%89%EC%98%88%EC%B8%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 환경 설정

In [ ]:
# 구글 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

# 드라이브에 저장된 폰트 등록
import matplotlib as mpl
import matplotlib.pyplot as plt # 그래프를 그리는 pyplot 모듈
import matplotlib.font_manager as fm # 폰트 관리 모듈

# 드라이브 내 폰트 경로
font_path = '/content/drive/MyDrive/kwu/Bigdata/dataPreProcessing/NanumGothic.ttf'

fm.fontManager.addfont(font_path)
mpl.rc('font',family='NanumGothic') #matplotlib 기본 폰트로 설정
plt.rcParams['font.family'] = 'NanumGothic'
plt.rcParams['font.sans-serif'] = ['NanumGothic', 'sans-serif']
plt.rcParams['axes.unicode_minus'] = False # 마이너스(-) 기호가 깨지지 않도록 비활성화

print("현재 폰트: ", plt.rcParams['font.family'])

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
현재 폰트:  ['NanumGothic']

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import xml.etree.ElementTree as ET
import warnings # 코드 실행 중 발생하는 불피요한 경고 메시지를 숨김
warnings.filterwarnings('ignore')
import pprint

### API에서 직접 데이터 수집하는 방법

In [59]:
#XML방식
api_key = '504c6e584f67696d34376a72614e41'
start=1 #시작 행 번호
end=1000 #끝 행 번호

url = (f'http://openapi.seoul.go.kr:8088/{api_key}/xml'
      f'/CardSubwayTime/{start}/{end}/202601/경원선/광운대')
#url = (f'http://openapi.seoul.go.kr:8088/{api_key}/xml'
#      f'/TbUseMonthstatusView/{start}/{end}/')

response = requests.get(url, timeout=10) #HTTP GET 요청을 보내고 응답을 받음, 최대 10초 대기
response

#XML 바이트 -> 트리 구조 파싱
root = ET.fromstring(response.content)

#전체 건수 확인 (list_total_count 태그)
total_tag = root.find('.//list_total_count') #.// 하위 해당 태그를 모두 찾음
if total_tag is not None:
  print(f'전체 데이터 건수: {total_tag.text}')

rows = []
for row in root.findall('.//row'): #모든 row태그 탐색
  rows.append({child.tag:child.text for child in row}) #각 <row>태그 내의 자식 태그(컬럼명)와 텍스트(설명)

df=pd.DataFrame(rows)

전체 데이터 건수: 1

In [61]:
print(df.columns)

Index(['USE_MM', 'SBWY_ROUT_LN_NM', 'STTN', 'HR_4_GET_ON_NOPE',
       'HR_4_GET_OFF_NOPE', 'HR_5_GET_ON_NOPE', 'HR_5_GET_OFF_NOPE',
       'HR_6_GET_ON_NOPE', 'HR_6_GET_OFF_NOPE', 'HR_7_GET_ON_NOPE',
       'HR_7_GET_OFF_NOPE', 'HR_8_GET_ON_NOPE', 'HR_8_GET_OFF_NOPE',
       'HR_9_GET_ON_NOPE', 'HR_9_GET_OFF_NOPE', 'HR_10_GET_ON_NOPE',
       'HR_10_GET_OFF_NOPE', 'HR_11_GET_ON_NOPE', 'HR_11_GET_OFF_NOPE',
       'HR_12_GET_ON_NOPE', 'HR_12_GET_OFF_NOPE', 'HR_13_GET_ON_NOPE',
       'HR_13_GET_OFF_NOPE', 'HR_14_GET_ON_NOPE', 'HR_14_GET_OFF_NOPE',
       'HR_15_GET_ON_NOPE', 'HR_15_GET_OFF_NOPE', 'HR_16_GET_ON_NOPE',
       'HR_16_GET_OFF_NOPE', 'HR_17_GET_ON_NOPE', 'HR_17_GET_OFF_NOPE',
       'HR_18_GET_ON_NOPE', 'HR_18_GET_OFF_NOPE', 'HR_19_GET_ON_NOPE',
       'HR_19_GET_OFF_NOPE', 'HR_20_GET_ON_NOPE', 'HR_20_GET_OFF_NOPE',
       'HR_21_GET_ON_NOPE', 'HR_21_GET_OFF_NOPE', 'HR_22_GET_ON_NOPE',
       'HR_22_GET_OFF_NOPE', 'HR_23_GET_ON_NOPE', 'HR_23_GET_OFF_NOPE',
       'HR_0_GET_ON_NOPE', 'HR_0_GET_OFF_NOPE', 'HR_1_GET_ON_NOPE',
       'HR_1_GET_OFF_NOPE', 'HR_2_GET_ON_NOPE', 'HR_2_GET_OFF_NOPE',
       'HR_3_GET_ON_NOPE', 'HR_3_GET_OFF_NOPE', 'JOB_YMD'],
      dtype='object')

In [60]:
df

,USE_MM,SBWY_ROUT_LN_NM,STTN,HR_4_GET_ON_NOPE,HR_4_GET_OFF_NOPE,HR_5_GET_ON_NOPE,HR_5_GET_OFF_NOPE,HR_6_GET_ON_NOPE,HR_6_GET_OFF_NOPE,HR_7_GET_ON_NOPE,...,HR_23_GET_OFF_NOPE,HR_0_GET_ON_NOPE,HR_0_GET_OFF_NOPE,HR_1_GET_ON_NOPE,HR_1_GET_OFF_NOPE,HR_2_GET_ON_NOPE,HR_2_GET_OFF_NOPE,HR_3_GET_ON_NOPE,HR_3_GET_OFF_NOPE,JOB_YMD
0,202601,경원선,광운대,2121,1,6310,1169,14307,3011,31022,...,9130,163,5117,0,2,0,0,0,0,20260203

In [ ]:
# JSON 방식
url = (f'http://openapi.seoul.go.kr:8088/{api_key}/json/'f'TbUseYearstatusView/{start}/{end}/')

data = requests.get(url, timeout=10).json() #JSON 방식으로 자동 파싱
pprint.pprint(data)

svc = data.get('TbUseMonthstatusView', {}) # 키의 값을 가져오기
print(f'전체 데이터 건수: {svc.get("list_total_count","알 수 없음")}')

df_j = pd.DataFrame(svc.get('row',[]))

{'TbUseYearstatusView': {'RESULT': {'CODE': 'INFO-000',
                                    'MESSAGE': '정상 처리되었습니다'},
                         'list_total_count': 197,
                         'row': [{'DSTRCT_TYPE': 'PLT-004',
                                  'DT': '2026',
                                  'PKLT_NM': '이촌1주차장',
                                  'PRK_CNTOM': 15047.0,
                                  'UTZTN_HR': 1369814.0},
                                 {'DSTRCT_TYPE': 'PLT-006',
                                  'DT': '2026',
                                  'PKLT_NM': '광나루1,2주차장',
                                  'PRK_CNTOM': 36526.0,
                                  'UTZTN_HR': 3331937.0},
                                 {'DSTRCT_TYPE': 'PLT-007',
                                  'DT': '2026',
                                  'PKLT_NM': '양화1주차장',
                                  'PRK_CNTOM': 16614.0,
                                  'UTZTN_HR': 1843016.0},
                                 {'DSTRCT_TYPE': 'PLT-011',
                                  'DT': '2026',
                                  'PKLT_NM': '잠실1주차장',
                                  'PRK_CNTOM': 115041.0,
                                  'UTZTN_HR': 4907825.0},
                                 {'DSTRCT_TYPE': 'PLT-007',
                                  'DT': '2026',
                                  'PKLT_NM': '양화3주차장',
                                  'PRK_CNTOM': 42771.0,
                                  'UTZTN_HR': 3679860.0},
                                 {'DSTRCT_TYPE': 'PLT-009',
                                  'DT': '2026',
                                  'PKLT_NM': '반포1주차장',
                                  'PRK_CNTOM': 42393.0,
                                  'UTZTN_HR': 2076658.0},
                                 {'DSTRCT_TYPE': 'PLT-004',
                                  'DT': '2026',
                                  'PKLT_NM': '이촌3주차장',
                                  'PRK_CNTOM': 64760.0,
                                  'UTZTN_HR': 6646396.0},
                                 {'DSTRCT_TYPE': 'PLT-008',
                                  'DT': '2026',
                                  'PKLT_NM': '여의도1주차장',
                                  'PRK_CNTOM': 128275.0,
                                  'UTZTN_HR': 20375230.0},
                                 {'DSTRCT_TYPE': 'PLT-008',
                                  'DT': '2026',
                                  'PKLT_NM': '여의도2주차장',
                                  'PRK_CNTOM': 65882.0,
                                  'UTZTN_HR': 8758525.0},
                                 {'DSTRCT_TYPE': 'PLT-003',
                                  'DT': '2026',
                                  'PKLT_NM': '망원2주차장',
                                  'PRK_CNTOM': 74686.0,
                                  'UTZTN_HR': 5876760.0},
                                 {'DSTRCT_TYPE': 'PLT-008',
                                  'DT': '2026',
                                  'PKLT_NM': '여의도4주차장',
                                  'PRK_CNTOM': 9154.0,
                                  'UTZTN_HR': 2767232.0},
                                 {'DSTRCT_TYPE': 'PLT-002',
                                  'DT': '2026',
                                  'PKLT_NM': '난지1,2,3,4주차장',
                                  'PRK_CNTOM': 107060.0,
                                  'UTZTN_HR': 5240197.0},
                                 {'DSTRCT_TYPE': 'PLT-005',
                                  'DT': '2026',
                                  'PKLT_NM': '뚝섬3주차장',
                                  'PRK_CNTOM': 36233.0,
                                  'UTZTN_HR': 3884998.0},
                                 {'DSTRCT_TYPE': 'PLT-007',
                                  'DT': '2026',
                                  'PKLT_NM': '양화2주차장',
                                  'PRK_CNTOM': 4193.0,
                                  'UTZTN_HR': 325902.0},
                                 {'DSTRCT_TYPE': 'PLT-006',
                                  'DT': '2026',
                                  'PKLT_NM': '광나루4주차장',
                                  'PRK_CNTOM': 19670.0,
                                  'UTZTN_HR': 2187476.0},
                                 {'DSTRCT_TYPE': 'PLT-005',
                                  'DT': '2026',
                                  'PKLT_NM': '뚝섬2주차장',
                                  'PRK_CNTOM': 49233.0,
                                  'UTZTN_HR': 6782390.0},
                                 {'DSTRCT_TYPE': 'PLT-003',
                                  'DT': '2026',
                                  'PKLT_NM': '망원1주차장',
                                  'PRK_CNTOM': 19477.0,
                                  'UTZTN_HR': 2259379.0},
                                 {'DSTRCT_TYPE': 'PLT-006',
                                  'DT': '2026',
                                  'PKLT_NM': '광나루3주차장',
                                  'PRK_CNTOM': 22768.0,
                                  'UTZTN_HR': 1967697.0},
                                 {'DSTRCT_TYPE': 'PLT-009',
                                  'DT': '2026',
                                  'PKLT_NM': '반포2,3주차장',
                                  'PRK_CNTOM': 162710.0,
                                  'UTZTN_HR': 21924622.0},
                                 {'DSTRCT_TYPE': 'PLT-008',
                                  'DT': '2026',
                                  'PKLT_NM': '여의도3주차장',
                                  'PRK_CNTOM': 98543.0,
                                  'UTZTN_HR': 24800850.0},
                                 {'DSTRCT_TYPE': 'PLT-004',
                                  'DT': '2026',
                                  'PKLT_NM': '이촌2주차장',
                                  'PRK_CNTOM': 24922.0,
                                  'UTZTN_HR': 4466835.0},
                                 {'DSTRCT_TYPE': 'PLT-005',
                                  'DT': '2026',
                                  'PKLT_NM': '뚝섬1주차장',
                                  'PRK_CNTOM': 14464.0,
                                  'UTZTN_HR': 1090387.0},
                                 {'DSTRCT_TYPE': 'PLT-008',
                                  'DT': '2026',
                                  'PKLT_NM': '여의도5주차장',
                                  'PRK_CNTOM': 22629.0,
                                  'UTZTN_HR': 6007417.0},
                                 {'DSTRCT_TYPE': 'PLT-011',
                                  'DT': '2026',
                                  'PKLT_NM': '잠실2,3주차장',
                                  'PRK_CNTOM': 29889.0,
                                  'UTZTN_HR': 3995366.0},
                                 {'DSTRCT_TYPE': 'PLT-010',
                                  'DT': '2026',
                                  'PKLT_NM': '잠원1주차장',
                                  'PRK_CNTOM': 37386.0,
                                  'UTZTN_HR': 3038241.0},
                                 {'DSTRCT_TYPE': 'PLT-001',
                                  'DT': '2026',
                                  'PKLT_NM': '강서1주차장',
                                  'PRK_CNTOM': 15091.0,
                                  'UTZTN_HR': 855641.0},
                                 {'DSTRCT_TYPE': 'PLT-005',
                                  'DT': '2026',
                                  'PKLT_NM': '뚝섬4주차장',
                                  'PRK_CNTOM': 45481.0,
                                  'UTZTN_HR': 4412917.0},
                                 {'DSTRCT_TYPE': 'PLT-010',
                                  'DT': '2026',
                                  'PKLT_NM': '잠원2-6주차장',
                                  'PRK_CNTOM': 115697.0,
                                  'UTZTN_HR': 13968849.0},
                                 {'DSTRCT_TYPE': 'PLT-010',
                                  'DT': '2025',
                                  'PKLT_NM': '잠원1주차장',
                                  'PRK_CNTOM': 210733.0,
                                  'UTZTN_HR': 17354247.0},
                                 {'DSTRCT_TYPE': 'PLT-005',
                                  'DT': '2025',
                                  'PKLT_NM': '뚝섬2주차장',
                                  'PRK_CNTOM': 272696.0,
                                  'UTZTN_HR': 39267661.0},
                                 {'DSTRCT_TYPE': 'PLT-008',
                                  'DT': '2025',
                                  'PKLT_NM': '여의도5주차장',
                                  'PRK_CNTOM': 108924.0,
                                  'UTZTN_HR': 27145109.0},
                                 {'DSTRCT_TYPE': 'PLT-006',
                                  'DT': '2025',
                                  'PKLT_NM': '광나루3주차장',
                                  'PRK_CNTOM': 170166.0,
                                  'UTZTN_HR': 13860369.0},
                                 {'DSTRCT_TYPE': 'PLT-011',
                                  'DT': '2025',
                                  'PKLT_NM': '잠실2,3주차장',
                                  'PRK_CNTOM': 177437.0,
                                  'UTZTN_HR': 21868371.0},
                                 {'DSTRCT_TYPE': 'PLT-003',
                                  'DT': '2025',
                                  'PKLT_NM': '망원2,3주차장',
                                  'PRK_CNTOM': 81786.0,
                                  'UTZTN_HR': 6551385.0},
                                 {'DSTRCT_TYPE': 'PLT-008',
                                  'DT': '2025',
                                  'PKLT_NM': '여의도4주차장',
                                  'PRK_CNTOM': 49842.0,
                                  'UTZTN_HR': 14628091.0},
                                 {'DSTRCT_TYPE': 'PLT-008',
                                  'DT': '2025',
                                  'PKLT_NM': '여의도2주차장',
                                  'PRK_CNTOM': 463091.0,
                                  'UTZTN_HR': 52025937.0},
                                 {'DSTRCT_TYPE': 'PLT-004',
                                  'DT': '2025',
                                  'PKLT_NM': '이촌1주차장',
                                  'PRK_CNTOM': 77972.0,
                                  'UTZTN_HR': 6251381.0},
                                 {'DSTRCT_TYPE': 'PLT-008',
                                  'DT': '2025',
                                  'PKLT_NM': '여의도1주차장',
                                  'PRK_CNTOM': 767721.0,
                                  'UTZTN_HR': 113223050.0},
                                 {'DSTRCT_TYPE': 'PLT-009',
                                  'DT': '2025',
                                  'PKLT_NM': '반포1주차장',
                                  'PRK_CNTOM': 276773.0,
                                  'UTZTN_HR': 18024274.0},
                                 {'DSTRCT_TYPE': 'PLT-005',
                                  'DT': '2025',
                                  'PKLT_NM': '뚝섬3주차장',
                                  'PRK_CNTOM': 178847.0,
                                  'UTZTN_HR': 20875519.0},
                                 {'DSTRCT_TYPE': 'PLT-005',
                                  'DT': '2025',
                                  'PKLT_NM': '뚝섬1주차장',
                                  'PRK_CNTOM': 81638.0,
                                  'UTZTN_HR': 6782152.0},
                                 {'DSTRCT_TYPE': 'PLT-011',
                                  'DT': '2025',
                                  'PKLT_NM': '잠실4주차장',
                                  'PRK_CNTOM': 95870.0,
                                  'UTZTN_HR': 4511018.0},
                                 {'DSTRCT_TYPE': 'PLT-006',
                                  'DT': '2025',
                                  'PKLT_NM': '광나루4주차장',
                                  'PRK_CNTOM': 96157.0,
                                  'UTZTN_HR': 6613873.0},
                                 {'DSTRCT_TYPE': 'PLT-007',
                                  'DT': '2025',
                                  'PKLT_NM': '양화2주차장',
                                  'PRK_CNTOM': 23143.0,
                                  'UTZTN_HR': 2257356.0},
                                 {'DSTRCT_TYPE': 'PLT-006',
                                  'DT': '2025',
                                  'PKLT_NM': '광나루1,2주차장',
                                  'PRK_CNTOM': 210370.0,
                                  'UTZTN_HR': 20186378.0},
                                 {'DSTRCT_TYPE': 'PLT-004',
                                  'DT': '2025',
                                  'PKLT_NM': '이촌2주차장',
                                  'PRK_CNTOM': 106791.0,
                                  'UTZTN_HR': 13134853.0},
                                 {'DSTRCT_TYPE': 'PLT-005',
                                  'DT': '2025',
                                  'PKLT_NM': '뚝섬4주차장',
                                  'PRK_CNTOM': 246764.0,
                                  'UTZTN_HR': 25183761.0},
                                 {'DSTRCT_TYPE': 'PLT-010',
                                  'DT': '2025',
                                  'PKLT_NM': '잠원2-6주차장',
                                  'PRK_CNTOM': 684880.0,
                                  'UTZTN_HR': 78619076.0},
                                 {'DSTRCT_TYPE': 'PLT-007',
                                  'DT': '2025',
                                  'PKLT_NM': '양화1주차장',
                                  'PRK_CNTOM': 101906.0,
                                  'UTZTN_HR': 12832259.0},
                                 {'DSTRCT_TYPE': 'PLT-008',
                                  'DT': '2025',
                                  'PKLT_NM': '여의도3주차장',
                                  'PRK_CNTOM': 521746.0,
                                  'UTZTN_HR': 121928255.0},
                                 {'DSTRCT_TYPE': 'PLT-001',
                                  'DT': '2025',
                                  'PKLT_NM': '강서1주차장',
                                  'PRK_CNTOM': 80419.0,
                                  'UTZTN_HR': 5637730.0},
                                 {'DSTRCT_TYPE': 'PLT-004',
                                  'DT': '2025',
                                  'PKLT_NM': '이촌3주차장',
                                  'PRK_CNTOM': 342619.0,
                                  'UTZTN_HR': 34393457.0},
                                 {'DSTRCT_TYPE': 'PLT-002',
                                  'DT': '2025',
                                  'PKLT_NM': '난지1,2,3주차장',
                                  'PRK_CNTOM': 131285.0,
                                  'UTZTN_HR': 5849532.0},
                                 {'DSTRCT_TYPE': 'PLT-003',
                                  'DT': '2025',
                                  'PKLT_NM': '망원1주차장',
                                  'PRK_CNTOM': 124259.0,
                                  'UTZTN_HR': 12469359.0},
                                 {'DSTRCT_TYPE': 'PLT-011',
                                  'DT': '2025',
                                  'PKLT_NM': '잠실2주차장',
                                  'PRK_CNTOM': 2848.0,
                                  'UTZTN_HR': 346170.0},
                                 {'DSTRCT_TYPE': 'PLT-007',
                                  'DT': '2025',
                                  'PKLT_NM': '양화3주차장',
                                  'PRK_CNTOM': 270362.0,
                                  'UTZTN_HR': 25739656.0},
                                 {'DSTRCT_TYPE': 'PLT-003',
                                  'DT': '2025',
                                  'PKLT_NM': '망원2주차장',
                                  'PRK_CNTOM': 282253.0,
                                  'UTZTN_HR': 23231908.0},
                                 {'DSTRCT_TYPE': 'PLT-002',
                                  'DT': '2025',
                                  'PKLT_NM': '난지1,2,3,4주차장',
                                  'PRK_CNTOM': 525876.0,
                                  'UTZTN_HR': 35118285.0},
                                 {'DSTRCT_TYPE': 'PLT-011',
                                  'DT': '2025',
                                  'PKLT_NM': '잠실1주차장',
                                  'PRK_CNTOM': 651291.0,
                                  'UTZTN_HR': 27845537.0},
                                 {'DSTRCT_TYPE': 'PLT-009',
                                  'DT': '2025',
                                  'PKLT_NM': '반포2,3주차장',
                                  'PRK_CNTOM': 966623.0,
                                  'UTZTN_HR': 108101991.0},
                                 {'DSTRCT_TYPE': 'PLT-009',
                                  'DT': '2024',
                                  'PKLT_NM': '반포2,3주차장',
                                  'PRK_CNTOM': 960692.0,
                                  'UTZTN_HR': 77121787.0},
                                 {'DSTRCT_TYPE': 'PLT-003',
                                  'DT': '2024',
                                  'PKLT_NM': '망원2,3주차장',
                                  'PRK_CNTOM': 362684.0,
                                  'UTZTN_HR': 31899161.0},
                                 {'DSTRCT_TYPE': 'PLT-010',
                                  'DT': '2024',
                                  'PKLT_NM': '잠원1주차장',
                                  'PRK_CNTOM': 166652.0,
                                  'UTZTN_HR': 14170769.0},
                                 {'DSTRCT_TYPE': 'PLT-006',
                                  'DT': '2024',
                                  'PKLT_NM': '광나루4주차장',
                                  'PRK_CNTOM': 90573.0,
                                  'UTZTN_HR': 4272955.0},
                                 {'DSTRCT_TYPE': 'PLT-008',
                                  'DT': '2024',
                                  'PKLT_NM': '여의도5주차장',
                                  'PRK_CNTOM': 108709.0,
                                  'UTZTN_HR': 26512412.0},
                                 {'DSTRCT_TYPE': 'PLT-008',
                                  'DT': '2024',
                                  'PKLT_NM': '여의도4주차장',
                                  'PRK_CNTOM': 57925.0,
                                  'UTZTN_HR': 16303113.0},
                                 {'DSTRCT_TYPE': 'PLT-004',
                                  'DT': '2024',
                                  'PKLT_NM': '이촌2주차장',
                                  'PRK_CNTOM': 98778.0,
                                  'UTZTN_HR': 9305627.0},
                                 {'DSTRCT_TYPE': 'PLT-005',
                                  'DT': '2024',
                                  'PKLT_NM': '뚝섬2주차장',
                                  'PRK_CNTOM': 275642.0,
                                  'UTZTN_HR': 34057665.0},
                                 {'DSTRCT_TYPE': 'PLT-008',
                                  'DT': '2024',
                                  'PKLT_NM': '여의도1주차장',
                                  'PRK_CNTOM': 772757.0,
                                  'UTZTN_HR': 104888013.0},
                                 {'DSTRCT_TYPE': 'PLT-004',
                                  'DT': '2024',
                                  'PKLT_NM': '이촌3주차장',
                                  'PRK_CNTOM': 47309.0,
                                  'UTZTN_HR': 4414864.0},
                                 {'DSTRCT_TYPE': 'PLT-011',
                                  'DT': '2024',
                                  'PKLT_NM': '잠실1주차장',
                                  'PRK_CNTOM': 649134.0,
                                  'UTZTN_HR': 25305359.0},

In [ ]:
df_j

Empty DataFrame
Columns: []
Index: []

In [ ]:
# csv 파일로 저장
BASE = '/content/drive/MyDrive/kwu/Bigdata/eda/서울시 지하철 호선별 역별 시간대별 승하차 인원 정보.csv'
PATH_DATA = BASE + 'TbUseMonthstatusView.csv'

df_j.to_csv(PATH_DATA, index=False, encoding='utf-8-sig')